# Generated by Django 3.1.7 on 2021-03-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtor_photo_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='realtor',
            name='lname',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
