# Generated by Django 3.1.7 on 2021-03-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_us',
        ),
    ]
