# Generated by Django 3.1.7 on 2021-03-10 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0004_auto_20210306_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amlak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField()),
                ('bathroom', models.IntegerField(default=2)),
                ('bedroom', models.IntegerField(default=1)),
                ('infrastructure', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 23, 11, 34, 82640))),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
